# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: TOP International
long_title: Tangolin Overseas Products International
description: >- # this means to ignore newlines until "baseurl:"
  We manufacture and distribute polymers and rubber compounds.
baseurl: "/top-international.github.io" # the subpath of your site, e.g. /blog
# url: "https://top.international" # the base hostname & protocol for your site, e.g. http://example.com
# twitter_username: jekyllrb
theme_color: 174a9c

## Collections ##
# collections_dir points to the directory collections will live.
collections_dir: collections

# collections lists each collection and sets options for each one.
# output: true is required if pages need to be rendered for each item.
collections:
  permalink: /:collection/:name
  markets:
    output: false
  products:
    output: true
    permalink: /suppliers-products/:name
  staff:
    output: false
    permalink: /about/:collection/:name
  suppliers:
    output: true
    permalink: /suppliers-products/:name

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
